#!/usr/bin/env bash

###
# Script to make running fuzzy5e as painless as possible.
# Requires docker-compose
###

idx_version="0.1.1"
idx_file="$HOME/.fuzzy5e-index"

function reindex() {
  echo "Updating index — this will take a minute..."
  docker-compose exec fuzzy5e bash -c 'SONIC_ADDR=sonic:1491 MONGO_ADDR=db:27017 fuzzy5e reindex'
  if [[ $? != 0 ]]; then
    echo "Indexing did not complete successfully." >&2
  else
    echo $idx_version > $idx_file
    echo "Done!" >&2
  fi
  docker-compose restart sonic
}

function index_version() {
  if [[ -f "$idx_file" ]]; then
    cat $idx_file
  else
    echo "0.0.0"
  fi
}

which docker-compose >/dev/null
if [[ $? != 0 ]]; then
  echo "docker-compose is required to run this script. Please install and ensure it is in your PATH." >&2
  exit 1
fi

echo "Starting search stack..."
docker-compose up -d

version=$(index_version)
if [[ $version < $idx_version ]]; then
  reindex
fi

winpty docker run --net fuzzy5e_default -it --entrypoint=fuzzy5e cjchance/fuzzy5e:0.1.5 --sonic-addr=sonic:1491 --mongo-addr=db:27017
